  name: Push into main branch
  on:
    push:
      branches: [ main ]

  env:
    MY_WORKFLOW_VARIABLE: "This is a workflow-level variable"      
   
  jobs:
    context:
      runs-on: ubuntu-latest
      env:
        MY_JOB_VARIABLE: "This is a job-level variable"
      steps:
      - name: Checkout
        uses: actions/checkout@v3
        env:
          MY_STEP_VARIABLE: "This is a step-level variable"
      
      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@1.13.1
        with:
          registry: registry.hub.docker.com
          organization: "mkaur0896"
          repository: "3345"
          login: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"
          platforms: linux/amd64,linux/arm64

      outputs:
        image: ${{ steps.build.outputs.image }}
        tag: ${{ steps.build.outputs.tag }}
    deploy:
      runs-on: ubuntu-latest
  
      steps:
      - name: Print Workflow variable
        run: echo $MY_WORKFLOW_VARIABLE
      - name: Print Job variable
        run: echo $MY_JOB_VARIABLE
      - name: Print Step variable
        run: echo $MY_STEP_VARIABLE

